resources:
  repositories:
  - repository: MyGitHubRepo3 # The name used to reference this repository in the checkout step
    type: github
    endpoint: test
    name: srkaranam/Test3
  - repository: MyGitHubRepo2 # The name used to reference this repository in the checkout step
    type: github
    endpoint: test
    name: srkaranam/Test2
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: test
    name: srkaranam/Test
    
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
- checkout: MyGitHubRepo3
- checkout: MyGitHubRepo2
- checkout: MyGitHubRepo

- script: dir $(Build.SourcesDirectory)