resources:
  repositories:

  - repository: MyGitHubRepo1 # The name used to reference this repository in the checkout step
    type: github
    endpoint: test
    name: srkaranam/Test2
  - repository: MyGitHubRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: test
    name: srkaranam/Test
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: MyGitHubRepo1
- checkout: MyGitHubRepo

- script: dir $(Build.SourcesDirectory)